### test API calls

### GET to root of api

GET http://localhost:8080 HTTP/1.1

### /api/customer API calls

### POST to create a Customer

POST http://localhost:8080/api/customer HTTP/1.1
Content-Type: application/json
